import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Leandro Fernandez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header>
        <div id="main-data">
            <h1>Leandro Fernandez</h1>
          </div>
          <ul className="personal-data">
            <li>
              <span>
                <Image src="/location-pointer.svg" alt="location icon" width={20} height={20} />{" "}
                Argentina
              </span>
            </li>
            <li>
              <span>
                <Image src="/email.svg" alt="email icon" width={20} height={20} />{" "}
                leandroofernandezz@gmail.com
              </span>
            </li>
            <li>
              <span>
                <Image src="/phone.svg" alt="phone icon" width={20} height={20} /> +54 1168521053
              </span>
            </li>
            <li>
              <span>
                <Image src="/github.svg" alt="github icon" width={20} height={20} />{" "}
                <a
                  href="https://github.com/leandroFernandez94"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  leandroFernandez94
                </a>
              </span>
            </li>
          </ul>
        </header>

        <hr className="main-line" />

        <h3 className="section-title">Profile</h3>
        <p>
          Web developer from Argentina, started coding in high school and never stopped since then.
          <br />
          Fullstack background, with most experience in frontend technologies, I have been working with
          react + node stacks for a long time(5+ years) building web apps.
          <br />
          I am always thinking about interesting ideas that can be transformed into helpful products. 
          I enjoy working with team mates and being helpful to them in any way I can while 
          I get feedback and learn from them at the same time
          <br />
          Elaborating solutions and finding ways to improve and document them is usually
          what motivates me the most. Making sure anyone who reads can understand them.
          {/* Looking for new projects where I can write production ready code,
          apply my experience in the development of web apps and find good
          working environments where I can help others and get good feedback. */}
        </p>
        <h3 className="section-title">Education</h3>
        <ul>
          <li>
            Currently focused on becoming a better self taught developer by
            applying to web courses and always looking for the newest
            technologies, accessibility
          </li>
          <li>Systems Engineering at UTN, 2013 - stopped in 2018</li>
          <li>
            Computer Technician at E.T. 35 D.E. 18 Ing. Eduardo Latzina, 2008 -
            2013
          </li>
          <li>English level: Firsts Certificate with a B qualification</li>
        </ul>
        <h3 className="section-title">Experience</h3>

        <h4>
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://www.sibly.com/"
          >
            Sibly
          </a>{" "}
          February 2021 - Present day:
        </h4>
        <ul>
          <li>First experience working remote with an international team</li>
          <li>
            Replatform: Finished ongoing project refactoring a jquery web app to React successfully
          </li>
          <li>
            Improved performance and code reliability issues adding typescript to the project.
          </li>
          <li>
            Developed new features working alongside product and designers team
          </li>
        </ul>


        <h4>
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://www.bons.io/"
          >
            Bons
          </a>{" "}
          October 2018 - January 2021:
        </h4>
        <ul>
          <li>
            Frontend development of{" "}
            <a
              target="_blank"
              rel="noopener noreferrer"
              href="https://www.produck.io/"
            >
              Produck
            </a>{" "}
            progressive web app made with react connected to backend with graphQL.
          </li>
          <li>
            Developed react and vuejs web apps integrated to{" "}
            <a
              target="_blank"
              rel="noopener noreferrer"
              href="https://webflow.com/"
            >
              webflow
            </a>{" "}
            for many of Bons clients. Using a custom stack with node + airtable
            + mongoDB in the backend served by vercel.
          </li>
        </ul>


        <h4>
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://despegar.com"
          >
            Despegar.com
          </a>{" "}
          August 2015 - October 2018:
        </h4>
        <ul>
          <li>
            Received training during &quot;Alto Vuelo&quot; course imparted by leaders of
            backend, frontend and mobile teams
          </li>
          <li>Development of REST APIs written in JAVA, SCALA and node.js</li>
          <li>Development of user interfaces based on angularjs and React</li>
        </ul>
        <h3 className="section-title">Key technologies I have worked with</h3>
        <ul>
          <li>
            <b>OS:</b> Linux, MacOS
          </li>
          <li>
            <b>Frontend stack: </b>React, Vue, Angular, Redux, Mobx State Tree, NextJS,
            Apollo(GraphQL), Webpack, PWAs
          </li>
          <li>
            <b>Backend stack: </b> Nodejs(with typescript) powered by
            express/vercel, MongoDB, sql based DBs, redis
          </li>
        </ul>
      </main>
    </div>
  )
}

export default Home
