import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Leandro Fernandez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header>
          <h1 id={styles.titleName}>Leandro Fernandez</h1>
          <ul className={styles.personalData}>
            <li className={styles.listItem}>
              <span>
                <Image
                  src="/location-pointer.svg"
                  alt="location icon"
                  width={20}
                  height={20}
                />{" "}
                Barcelona, Spain
              </span>
            </li>
            <li className={styles.listItem}>
              <span>
                <Image
                  src="/email.svg"
                  alt="email icon"
                  width={20}
                  height={20}
                />{" "}
                leandroofernandezz@gmail.com
              </span>
            </li>
            <li className={styles.listItem}>
              <span>
                <Image
                  src="/linkedinIcon.svg"
                  alt="linkedin icon"
                  width={20}
                  height={20}
                />{" "}
                <a
                  className={styles.link}
                  href="https://www.linkedin.com/in/leandro-fernandez-dev"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  /leandro-fernandez-dev
                </a>
              </span>
            </li>
            <li className={styles.listItem}>
              <span>
                <Image
                  src="/github.svg"
                  alt="github icon"
                  width={20}
                  height={20}
                />{" "}
                <a
                  className={styles.link}
                  href="https://github.com/leandroFernandez94"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  /leandroFernandez94
                </a>
              </span>
            </li>
          </ul>
        </header>
        <hr className={styles.mainLine} />
        <h3 className={styles.sectionTitle}>About me</h3>I am Web developer from
        Argentina. I am currently living in Barcelona, Spain. <br></br>I can do
        both backend and frontend, but most of my experience is related to
        frontend technologies, I have been working with React + Node.js stacks
        for a long time(5+ years) building web apps.
        <h4>Things I find motivating:</h4>
        <ul>
          <li className={styles.listItem}>
            Coming up with ideas that could be transformed into helpful
            utilities.
          </li>
          <li className={styles.listItem}>
            Elaborating solutions for challenging technical problems and
            documenting them the best way I can.
          </li>
          <li className={styles.listItem}>
            Finding ways to improve the UX of the projects I work on.
          </li>
        </ul>
        {/* I enjoy working with my team mates and being helpful to them in any way I can, I also consider
          being a nice person to everyone an essential part of my daily routine */}
        {/* <br /> */}
        {/* Elaborating solutions for challenging technical problems and finding ways to improve the UX 
          in my projects is very important to me. Part of my responsability as an engineer is making 
          sure anyone who reads my code can understand it and add value to it. */}
        {/* Looking for new projects where I can write production ready code,
          apply my experience in the development of web apps and find good
          working environments where I can help others and get good feedback. */}
        <h3 className={styles.sectionTitle}>Education</h3>
        <ul>
          <li className={styles.listItem}>
            Currently focused on applying to courses and workshops to keep
            myself updated in terms of new technologies that can help me become
            a better engineer.
          </li>
          <li className={styles.listItem}>
            Systems Engineering at{" "}
            <a
              className={styles.link}
              href="https://en.wikipedia.org/wiki/National_Technological_University"
              target="_blank"
              rel="noopener noreferrer"
            >
              UTN
            </a>
            , 2013 - dropped in 2018.
          </li>
          <li className={styles.listItem}>
            Computer Technician at E.T. 35 D.E. 18 Ing. Eduardo Latzina, 2008 -
            2013.
          </li>
          <li className={styles.listItem}>
            Languages I speak:
            <ul>Spanish(native).</ul>
            <ul>English: conversational level. Approved first certificate.</ul>
          </li>
        </ul>
        <h3 className={styles.sectionTitle}>Experience</h3>
        <h4>
          Working for{" "}
          <a
            className={styles.link}
            target="_blank"
            rel="noopener noreferrer"
            href="https://capitole-consulting.com/"
          >
            Capitole Consulting:
          </a>
        </h4>
        <ul>
          <h4>
            <a
              className={styles.link}
              target="_blank"
              rel="noopener noreferrer"
              href="https://www.axa.com/"
            >
              AXA:
            </a>{" "}
            May 2023 - present day:
          </h4>
          <ul>
            <li className={styles.listItem}>
              Contributed to the frontend of the Axa Partners group of
              applications, working on a set of React apps customizable for
              different partners through configuration and internationalization.
            </li>
            <li className={styles.listItem}>
              Worked on the integration of PWA support for the apps.
            </li>
            <li>
              Gained experience in the Azure cloud platform working on
              configurations for deployment pipelines and different
              automatization scripts.
            </li>
          </ul>
        </ul>
        <h4>
          Working as a contractor for{" "}
          <a
            className={styles.link}
            target="_blank"
            rel="noopener noreferrer"
            href="https://www.devborn.com/"
          >
            Devborn:
          </a>
        </h4>
        <ul>
          <h4>
            <a
              className={styles.link}
              target="_blank"
              rel="noopener noreferrer"
              href="https://www.fabfitfun.com/"
            >
              FabFitFun:
            </a>{" "}
            January 2023 - April 2023:
          </h4>
          <ul>
            <li className={styles.listItem}>
              Working remotely with the web team on an ecommerce platform that
              sells seasonal boxes of beauty, wellness, fashion, and fitness
              products.
            </li>
            <li className={styles.listItem}>
              Improve integration of A/B testing using Optimizely.
            </li>
          </ul>
          <h4>
            <a
              className={styles.link}
              target="_blank"
              rel="noopener noreferrer"
              href="https://www.sibly.com/"
            >
              Sibly:
            </a>{" "}
            February 2021 - December 2022:
          </h4>
          <ul>
            <li className={styles.listItem}>
              First experience working remotely with an international team.
            </li>
            <li className={styles.listItem}>
              Replatform: Accomplished a project to refactor an old jquery web
              app into a new React dashboard.
            </li>
            <li className={styles.listItem}>
              Improved performance and code reliability issues adding typescript
              to the project.
            </li>
            <li className={styles.listItem}>
              Added jest unit tests to improve code coverage on both components
              and Store logic.
            </li>
            <li className={styles.listItem}>
              Developed new features working alongside product and designers
              team.
            </li>
            <li className={styles.listItem}>
              Dealt with complex challenges related to websockets and messaging
              events using sendbird SDK.
            </li>
            <li className={styles.listItem}>
              Worked on timezone dependant features for a webapp used by people
              in different zones of the world.
            </li>
            <li className={styles.listItem}>
              Lead the development of a new web platform for users of sibly.
            </li>
            <li className={styles.listItem}>
              Experience using an AWS setup with s3 and cloudfront.
            </li>
          </ul>
        </ul>
        <h4>
          <a
            className={styles.link}
            target="_blank"
            rel="noopener noreferrer"
            href="https://www.bons.io/"
          >
            Bons:
          </a>{" "}
          October 2018 - January 2021:
        </h4>
        <ul>
          <li className={styles.listItem}>
            Frontend development of{" "}
            <a
              className={styles.link}
              target="_blank"
              rel="noopener noreferrer"
              href="https://www.produck.io/"
            >
              Produck
            </a>{" "}
            Progressive web app built with React and connected to a backend
            using graphQL query language.
          </li>
          <li className={styles.listItem}>
            Implemented performance improvements to a React app that has complex
            components connected to a very large state using the apollo graphQL
            client while also considering optimistic results and caching
            strategies.
          </li>
          <li className={styles.listItem}>
            Developed a web push notifications feature for produck&apos;s webapp
            notifications system.
          </li>
          <li className={styles.listItem}>
            Developed react and vuejs web apps integrated to{" "}
            <a
              className={styles.link}
              target="_blank"
              rel="noopener noreferrer"
              href="https://webflow.com/"
            >
              webflow
            </a>{" "}
            for many of Bons clients. Using a custom stack with nodeJS +
            airtable + mongoDB in the backend served by a Vercel serverless BE.
          </li>
        </ul>
        <h4>
          <a
            className={styles.link}
            target="_blank"
            rel="noopener noreferrer"
            href="https://despegar.com"
          >
            Despegar.com:
          </a>{" "}
          August 2015 - October 2018:
        </h4>
        <ul>
          <li className={styles.listItem}>
            Received training during &quot;Alto Vuelo&quot; course imparted by
            leaders of backend, frontend and mobile teams.
          </li>
          <li className={styles.listItem}>
            Development of REST APIs written in JAVA, SCALA and node.js.
          </li>
          <li className={styles.listItem}>
            Development of user interfaces powered by angularjs and React.
          </li>
        </ul>
        {/* <h3 className={styles.sectionTitle}>Key technologies I have worked with</h3>
        <ul>
          <li className={styles.listItem}>
            <b>OS:</b> Linux, MacOS
          </li>
          <li className={styles.listItem}>
            <b>Frontend stack: </b>React, Vue, Angular, Redux, Mobx State Tree, NextJS,
            Apollo(GraphQL), Webpack, PWAs
          </li>
          <li className={styles.listItem}>
            <b>Backend stack: </b> Nodejs(with typescript) powered by
            express/vercel, MongoDB, sql based DBs, redis
          </li>
        </ul> */}
      </main>
    </div>
  );
};

export default Home;
